name: WolfyUtilities
version: '${project.version}'
main: com.wolfyscript.utilities.paper.WolfyCorePaper
api-version: '1.19' # This config was introduced in 1.19, so it can only be loaded on 1.19+ servers!
authors: [ WolfyScript ]
load: STARTUP

libraries:
  - "com.google.inject:guice:5.1.0"
  - "org.apache.commons:commons-lang3:3.12.0"
  - "it.unimi.dsi:fastutil:8.5.6"

dependencies:
  server:
    Magic:
      required: false
      load: OMIT
    LWC:
      required: false
      load: OMIT
    PlotSquared:
      required: false
      load: OMIT
    WorldGuard:
      required: false
      load: OMIT
    Oraxen:
      required: false
      load: OMIT
    ItemsAdder:
      required: false
      load: OMIT
    PlaceholderAPI:
      required: false
      load: OMIT
    eco:
      required: false
      load: OMIT
    Denizen:
      required: false
      load: OMIT
    # Mythic Plugins
    MythicMobs:
      required: false
      load: OMIT
    MMOItems:
      required: false
      load: OMIT
    mcMMO:
      required: false
      load: OMIT
    # SCore Plugins
    SCore:
      load: BEFORE
      required: false
    ExecutableItems:
      required: false
      load: OMIT
    ExecutableBlocks:
      required: false
      load: OMIT
    # Plugins that must load after WolfyUtils
    ChatColor:
      load: AFTER
      required: false
    ChatColor2:
      load: AFTER
      required: false
    StackableItems:
      load: AFTER
      required: false
    DiSky:
      load: AFTER
      required: false
    EpicWorldGenerator:
      load: AFTER
      required: false
    zAuctionHouseV3:
      load: BEFORE
      required: false
    BungeeChat:
      load: BEFORE
      required: false

permissions:
  wolfyutilities.command.query_debug:
    default: op
    description: "Command to debug NBT querries on the item in the hand"
